version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go-client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/python-client"
    schedule:
      interval: "weekly"
